# Generated by Django 2.0.2 on 2018-02-23 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('sent_score', models.IntegerField(default=0)),
                ('sent_mag', models.IntegerField(default=0)),
                ('emo_happy', models.IntegerField(default=0)),
                ('emo_sad', models.IntegerField(default=0)),
                ('emo_suprised', models.IntegerField(default=0)),
                ('emo_angry', models.IntegerField(default=0)),
                ('emo_bored', models.IntegerField(default=0)),
                ('emo_empty', models.IntegerField(default=0)),
                ('emo_enthusiasm', models.IntegerField(default=0)),
                ('emo_neutral', models.IntegerField(default=0)),
                ('emo_worry', models.IntegerField(default=0)),
                ('emo_love', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('content', models.TextField()),
                ('sent_score', models.IntegerField(default=0)),
                ('sent_mag', models.IntegerField(default=0)),
                ('emo_happy', models.IntegerField(default=0)),
                ('emo_sad', models.IntegerField(default=0)),
                ('emo_suprised', models.IntegerField(default=0)),
                ('emo_angry', models.IntegerField(default=0)),
                ('emo_bored', models.IntegerField(default=0)),
                ('emo_empty', models.IntegerField(default=0)),
                ('emo_enthusiasm', models.IntegerField(default=0)),
                ('emo_neutral', models.IntegerField(default=0)),
                ('emo_worry', models.IntegerField(default=0)),
                ('emo_love', models.IntegerField(default=0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SRP.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sent_score', models.IntegerField(default=0)),
                ('sent_mag', models.IntegerField(default=0)),
                ('emo_happy', models.IntegerField(default=0)),
                ('emo_sad', models.IntegerField(default=0)),
                ('emo_suprised', models.IntegerField(default=0)),
                ('emo_angry', models.IntegerField(default=0)),
                ('emo_bored', models.IntegerField(default=0)),
                ('emo_empty', models.IntegerField(default=0)),
                ('emo_enthusiasm', models.IntegerField(default=0)),
                ('emo_neutral', models.IntegerField(default=0)),
                ('emo_worry', models.IntegerField(default=0)),
                ('emo_love', models.IntegerField(default=0)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SRP.Experience')),
            ],
        ),
    ]
