# Generated by Django 2.0.2 on 2018-02-23 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SRP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_t', models.IntegerField()),
                ('sent_score', models.IntegerField(default=0)),
                ('sent_mag', models.IntegerField(default=0)),
                ('emo_happy', models.IntegerField(default=0)),
                ('emo_sad', models.IntegerField(default=0)),
                ('emo_suprised', models.IntegerField(default=0)),
                ('emo_angry', models.IntegerField(default=0)),
                ('emo_bored', models.IntegerField(default=0)),
                ('emo_empty', models.IntegerField(default=0)),
                ('emo_enthusiasm', models.IntegerField(default=0)),
                ('emo_neutral', models.IntegerField(default=0)),
                ('emo_worry', models.IntegerField(default=0)),
                ('emo_love', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='current_t',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experience',
            name='create_t',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentence',
            name='create_t',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noun',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SRP.Entity'),
        ),
        migrations.AddField(
            model_name='noun',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SRP.Experience'),
        ),
    ]
