# Generated by Django 2.0.2 on 2018-02-23 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SRP', '0002_auto_20180223_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noun',
            old_name='content',
            new_name='noun',
        ),
    ]
